<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Otel.Kafka.Interceptors.StartupHook</AssemblyName>
    <RootNamespace>Otel.Kafka.Interceptors.StartupHook</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\\Otel.Kafka.Interceptors.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.0" />
  </ItemGroup>
</Project>
